methods:
  - lightgbm
  - fairgbm
  - Random Forest + Undersampling
  - Logistic Regression + Group Threshold

datasets:
  - baf_sample

optimization:
  n_trials: 50
  n_jobs: 1
  sampler: RandomSampler
  sampler_args:
    seed: 42
