baf_variant_1:
  classpath: aequitas.fairflow.datasets.BankAccountFraud
  sensitive_attribute: customer_age_bin
  label: fraud_bool
  threshold:
    threshold_type: fpr
    threshold_value: 0.05
  args: 
    variant: TypeI
