exponentiated_gradient:
  classpath: aequitas.fairflow.methods.inprocessing.fairlearn_classifier.FairlearnClassifier
  args:
    reduction:
      - fairlearn.reductions.ExponentiatedGradient

    estimator:
      - lightgbm.LGBMClassifier

    constraint:
      - fairlearn.reductions.FalsePositiveRateParity

    eps:
      type: float
      range: [ 0.005, 0.5 ]
      log: True

    max_iter:
      - 10
    
    model__boosting_type:
      - dart  #  Running DART for all algos

    model__enable_bundle:
      - False

    model__n_estimators:
      type: int
      range: [100, 1000]

    model__num_leaves:
      type: int
      range: [10, 1000]

    model__min_child_samples:
      type: int
      range: [1, 500]
      log: True

    model__learning_rate:
      type: float
      range: [0.001, 0.1]

    model__n_jobs:
      - 1