prevalence_sampling:
  args:
    alpha: 
      type: float
      range: [0.5, 1]
    strategy:
      - oversample
  classpath: aequitas.fairflow.methods.preprocessing.prevalence_sample.PrevalenceSampling