lightgbm:
  classpath: aequitas.fairflow.methods.base_estimator.RandomForest
  args:
    n_estimators:
      type: int
      range: [10, 100]

    min_samples_in_leaf:
      type: int
      range: [1, 500]
      log: True
