methods:
  - lightgbm_baseline
  - prevalence_undersampling
  - prevalence_oversampling
  - fairgbm_folktables
  - group_threshold_folktables
  - grid_search_folktables
  - exponentiated_gradient_folktables

datasets:
  - FolkTables_ACSEmployment
  - FolkTables_ACSIncome
  - FolkTables_ACSPublicCoverage
  - FolkTables_ACSMobility
  - FolkTables_ACSTravelTime

optimization:
  n_trials: 100
  n_jobs: 1
  sampler: RandomSampler
  sampler_args:
    seed: 42
