fairgbm:
  classpath: aequitas.fairflow.methods.inprocessing.fairgbm.FairGBM
  args:
    global_constraint_type:
      - FPR,FNR
    
    global_target_fpr:
      - 0.05
    
    global_target_fnr:
      type: float
      range: [0.4, 0.6]

    constraint_type:
      - FPR

    constraint_fpr_threshold:
      - 0
    
    proxy_margin:
      - 1

    multiplier_learning_rate:
      type: float
      range: [0.00001, 1.0]
      log: True
    
    constraint_stepwise_proxy:
      - cross_entropy

    boosting_type:
      - dart
      - gbdt

    enable_bundle:
      - False

    n_estimators:
      type: int
      range: [10, 100]

    min_child_samples:
      type: int
      range: [1, 500]
      log: True

    learning_rate:
      type: float
      range: [0.001, 0.1]

    n_jobs:
      - 1